---
controller_hosts:
- name: localhost
  inventory: AAP Managed Inventory
  variables:
    ansible_host: '127.0.0.1'
    ansible_connection: 'local'
- name: localhost
  inventory: Datacenter 1
  variables:
    ansible_host: '127.0.0.1'
    ansible_connection: 'local'