---
hub_collection_remotes:
  - name: community
    url: https://galaxy.ansible.com/api/
    sync_dependencies: true
    requirements:
      - name: community.general
        version: 12.0.1
      - name: containers.podman
        version: 1.18.0
      - name: community.hashi_vault
        version: 7.1.0
      - name: community.crypto
        version: 3.0.5

  - name: validated
    url: https://console.redhat.com/api/automation-hub/content/validated/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    token: "{{ red_hat_auto_hub_token }}"
    sync_dependencies: true
    requirements:
      - name: infra.aap_configuration
        version: 3.8.4

  - name: rh-certified
    url: https://console.redhat.com/api/automation-hub/content/published/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
    token: "{{ red_hat_auto_hub_token }}"
    sync_dependencies: true
    requirements:
      - name: ansible.controller
        version: 4.7.5
      - name: ansible.eda
        version: 2.10.0
      - name: ansible.hub
        version: 1.0.3
      - name: ansible.platform
        version: 2.6.20251106
      - name: ansible.posix
        version: 2.1.0
      - name: ansible.utils
        version: 6.0.0
      - name: redhat.rhel_system_roles
        version: 1.108.6
