---
hub_collection_remotes:
  - name: community
    url: https://galaxy.ansible.com/api/
    sync_dependencies: true
    requirements:
      - name: community.general
        version: 12.0.1
      - name: containers.podman
        version: 1.18.0
      - name: community.hashi_vault
        version: 7.1.0
      - name: community.crypto
        version: 3.0.5